# Generated by Django 3.1.1 on 2020-09-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahh', '0002_auto_20200926_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='specialty',
            field=models.TextField(default='عام'),
        ),
    ]
