# Generated by Django 3.1.1 on 2020-10-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahh', '0005_auto_20201002_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='time',
            field=models.CharField(choices=[(1, 'صباحي'), (2, 'مسائي')], default=1, max_length=10),
        ),
    ]
