# Generated by Django 3.1.1 on 2020-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahh', '0006_auto_20201002_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='installment',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='courses',
            name='shares',
            field=models.IntegerField(default=-1),
        ),
    ]
