# Generated by Django 3.1.1 on 2020-10-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahh', '0007_auto_20201002_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='note',
            field=models.TextField(default='لا يوجد'),
        ),
    ]
