# Generated by Django 3.1.1 on 2020-10-03 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahh', '0008_enterprise_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sahh.enterprise'),
        ),
    ]
