# Generated by Django 3.1.1 on 2020-10-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahh', '0009_nursery_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='price',
            field=models.FloatField(default=0.0, max_length=20),
        ),
    ]
